from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import json, os, webbrowser, threading

from logfiles    import generate_log
from hash_chain  import apply_hash_chain
from verify_logs import verify_logs, GENESIS_HASH, compute_hash

app = Flask(__name__)
CORS(app)

LOG_FILE    = "logs.jsonl"
REPORT_FILE = "audit_report.txt"


# ── Serve the frontend
@app.route('/')
def index():
    return send_file('Front_end_tamper.html')


# ── GET /logs  — return raw contents of logs.jsonl as a JSON array
@app.route('/logs', methods=['GET'])
def get_logs():
    if not os.path.exists(LOG_FILE):
        return jsonify([])
    logs = []
    with open(LOG_FILE, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                logs.append(json.loads(line))
    return jsonify(logs)


# ── POST /add  { "event_type": "LOGIN", "message": "User admin logged in" }
@app.route('/add', methods=['POST'])
def add_log():
    data = request.get_json()
    generate_log(data['event_type'], data['message'])
    return jsonify({'status': 'ok'})


# ── POST /hash  — apply SHA-256 hash chain across logs.jsonl
@app.route('/hash', methods=['POST'])
def apply_hash():
    apply_hash_chain()
    return jsonify({'status': 'ok'})


# ── GET /verify  — verify chain integrity, return per-log results + summary
@app.route('/verify', methods=['GET'])
def do_verify():
    verify_logs()          # writes audit_report.txt (existing logic, untouched)

    # Load logs
    logs = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line:
                    logs.append(json.loads(line))

    # Compute per-entry validity so the frontend can colour each row
    # (verify_logs() stops at first failure; we need all entries marked)
    prev = GENESIS_HASH
    for log in logs:
        h_in     = f"{log['log_id']}|{log['timestamp']}|{log['event_type']}|{log['message']}|{prev}"
        computed = compute_hash(h_in)
        log['is_valid']    = (computed == log['current_hash'])
        log['tamper_type'] = None if log['is_valid'] else 'modified'
        prev = log['current_hash']

    # Read the audit report written by verify_logs()
    report_text = ''
    if os.path.exists(REPORT_FILE):
        with open(REPORT_FILE, 'r') as f:
            report_text = f.read()

    tampered_entries = [
        {
            'index':     l['log_id'],
            'type':      l['tamper_type'],
            'message':   f"Hash mismatch at Log #{l['log_id']}. Entry was modified after hashing.",
            'timestamp': l['timestamp'],
        }
        for l in logs if not l['is_valid']
    ]

    return jsonify({
        'isValid':         len(tampered_entries) == 0,
        'totalLogs':       len(logs),
        'validLogs':       sum(1 for l in logs if l['is_valid']),
        'tamperedLogs':    len(tampered_entries),
        'tamperedEntries': tampered_entries,
        'logs':            logs,
        'report':          report_text,
    })


# ── GET /report  — download the raw audit_report.txt generated by verify_logs()
@app.route('/report', methods=['GET'])
def get_report():
    if not os.path.exists(REPORT_FILE):
        return 'No audit report found. Run verify first.', 404
    return send_file(REPORT_FILE, mimetype='text/plain')


if __name__ == '__main__':
    threading.Timer(1.0, lambda: webbrowser.open('http://localhost:5000')).start()
    app.run(debug=False, port=5000)
